# About me
title: Nikhil Verma
author: Nikhil Verma
description: ""
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://nikhilweee.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Social media
twitter_username: nikhilweee
github_username: nikhilweee
linkedin_username: nikhilweee

# Analytics
google_analytics: UA-72048305-1
comments: true

# Comments
disqus: nikhilweee

# Navigation
permalink: /:collection/:title/

# Build settings
markdown: kramdown

# jekyll-archives
jekyll-archives:
  enabled:
    - tags
    - categories
  layout: categories

# jekyll-gist
gist:
  noscript: false

# jekyll-paginate
pagination:
  enabled: true
  per_page: 20


# Excludes
exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - README.md
  - LICENSE.txt
